services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: noveltygraph_joules
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    env_file:
      - development.env

    command: sh -c "node server.js"
